grafana:
  enabled: false
alertmanager:
  enabled: false
prometheus:
  service:
    type: NodePort
    nodePort: 30090
  prometheusSpec:
    scrapeInterval: 15s
    evaluationInterval: 15s
    retention: 1d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
